# Generated by Django 5.2 on 2026-02-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='age',
            field=models.IntegerField(blank=True, help_text='Age in years. Fractional if less than 1', null=True, verbose_name='Age'),
        ),
    ]
