# Generated by Django 5.2 on 2026-02-09 11:43

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_id', models.IntegerField(help_text='Unique identifier from the Titanic dataset', unique=True, verbose_name='Passenger ID')),
                ('survived', models.BooleanField(help_text='Actual survival outcome (True = Survived, False = Did Not Survive)', verbose_name='Survived')),
                ('pclass', models.IntegerField(choices=[(1, 'First Class'), (2, 'Second Class'), (3, 'Third Class')], help_text='Ticket class (1 = 1st, 2 = 2nd, 3 = 3rd)', verbose_name='Passenger Class')),
                ('name', models.CharField(help_text='Full name including title', max_length=200, verbose_name='Passenger Name')),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10, verbose_name='Gender')),
                ('age', models.FloatField(blank=True, help_text='Age in years. Fractional if less than 1', null=True, verbose_name='Age')),
                ('sibsp', models.IntegerField(default=0, help_text='Number of siblings or spouses aboard', verbose_name='Siblings/Spouses Aboard')),
                ('parch', models.IntegerField(default=0, help_text='Number of parents or children aboard', verbose_name='Parents/Children Aboard')),
                ('ticket', models.CharField(max_length=50, verbose_name='Ticket Number')),
                ('fare', models.DecimalField(blank=True, decimal_places=4, help_text='Passenger fare in pounds', max_digits=10, null=True, verbose_name='Fare')),
                ('cabin', models.CharField(blank=True, help_text='Cabin number', max_length=20, verbose_name='Cabin')),
                ('embarked', models.CharField(blank=True, choices=[('C', 'Cherbourg'), ('Q', 'Queenstown'), ('S', 'Southampton')], max_length=1, verbose_name='Port of Embarkation')),
                ('family_size', models.IntegerField(blank=True, help_text='Calculated as SibSp + Parch + 1', null=True, verbose_name='Family Size')),
                ('age_group', models.CharField(choices=[('infant', 'Infant (0-2)'), ('child', 'Child (3-12)'), ('teen', 'Teenager (13-19)'), ('young_adult', 'Young Adult (20-29)'), ('adult', 'Adult (30-59)'), ('senior', 'Senior (60+)'), ('unknown', 'Unknown')], default='unknown', help_text='Age group calculated from age', max_length=15, verbose_name='Age Group')),
                ('data_source', models.CharField(choices=[('train', 'Training Data'), ('test', 'Test Data')], default='train', help_text='Whether this record is from training or test dataset', max_length=10, verbose_name='Data Source')),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Imported At')),
            ],
            options={
                'verbose_name': 'Titanic Passenger',
                'verbose_name_plural': 'Titanic Passengers',
                'ordering': ['passenger_id'],
            },
        ),
        migrations.CreateModel(
            name='PredictionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name for prediction', max_length=200, verbose_name='Passenger Name')),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10, verbose_name='Gender')),
                ('age', models.FloatField(help_text='Age in years', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)], verbose_name='Age')),
                ('parch', models.IntegerField(default=0, help_text='Number of parents or children traveling with', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Parents/Children Aboard')),
                ('embarked', models.CharField(choices=[('C', 'Cherbourg'), ('Q', 'Queenstown'), ('S', 'Southampton')], max_length=1, verbose_name='Port of Embarkation')),
                ('sibsp', models.IntegerField(default=0, help_text='Optional: Number of siblings or spouses traveling with', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Siblings/Spouses Aboard')),
                ('ticket', models.CharField(blank=True, help_text='Optional: Ticket number', max_length=50, verbose_name='Ticket Number')),
                ('fare', models.DecimalField(blank=True, decimal_places=2, help_text='Optional: Ticket fare in pounds', max_digits=10, null=True, verbose_name='Fare')),
                ('cabin', models.CharField(blank=True, help_text='Optional: Cabin number', max_length=20, verbose_name='Cabin Number')),
                ('family_size', models.IntegerField(blank=True, help_text='Calculated as SibSp + Parch + 1', null=True, verbose_name='Family Size')),
                ('age_group', models.CharField(blank=True, choices=[('infant', 'Infant (0-2)'), ('child', 'Child (3-12)'), ('teen', 'Teenager (13-19)'), ('young_adult', 'Young Adult (20-29)'), ('adult', 'Adult (30-59)'), ('senior', 'Senior (60+)'), ('unknown', 'Unknown')], max_length=15, verbose_name='Age Group')),
                ('survived_prediction', models.BooleanField(blank=True, null=True, verbose_name='Survival Prediction')),
                ('probability', models.FloatField(blank=True, help_text='Probability of survival between 0.0 and 1.0', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Survival Probability')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Prediction Timestamp')),
            ],
            options={
                'verbose_name': 'Prediction Record',
                'verbose_name_plural': 'Prediction Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
