# Generated by Django 5.2 on 2026-02-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='age',
            field=models.FloatField(blank=True, help_text='Age in years(integer). Null if unknown.', null=True, verbose_name='Age'),
        ),
    ]
