# Generated by Django 5.2 on 2026-02-11 13:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_passenger_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='age',
            field=models.IntegerField(blank=True, help_text='Age in years(integer). Null if unknown.', null=True, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='predictionrecord',
            name='age',
            field=models.IntegerField(help_text='Age in years', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)], verbose_name='Age'),
        ),
    ]
