# Generated by Django 5.2 on 2026-02-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_passenger_age_alter_predictionrecord_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='features_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
