# Generated by Django 5.2 on 2026-02-11 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_remove_features_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='features_json',
        ),
    ]
