# Generated by Django 5.2 on 2026-02-11 14:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_remove_features_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionrecord',
            name='age',
            field=models.IntegerField(help_text='Age in years(integer)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)], verbose_name='Age'),
        ),
    ]
