# Generated by Django 5.2 on 2026-02-12 15:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_predictionrecord_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictionrecord',
            name='cabin',
        ),
        migrations.RemoveField(
            model_name='predictionrecord',
            name='ticket',
        ),
        migrations.AddField(
            model_name='predictionrecord',
            name='pclass',
            field=models.IntegerField(choices=[(1, 'First Class'), (2, 'Second Class'), (3, 'Third Class')], default=1, help_text='Ticket class (1 = 1st, 2 = 2nd, 3 = 3rd)', verbose_name='Passenger Class'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='predictionrecord',
            name='age_group',
            field=models.CharField(blank=True, choices=[('infant', 'Infant (0-2)'), ('child', 'Child (3-12)'), ('teen', 'Teenager (13-19)'), ('young_adult', 'Young Adult (20-29)'), ('adult', 'Adult (30-59)'), ('senior', 'Senior (60+)'), ('unknown', 'Unknown')], editable=False, max_length=15, verbose_name='Age Group'),
        ),
        migrations.AlterField(
            model_name='predictionrecord',
            name='family_size',
            field=models.IntegerField(blank=True, editable=False, help_text='Calculated as SibSp + Parch + 1', null=True, verbose_name='Family Size'),
        ),
        migrations.AlterField(
            model_name='predictionrecord',
            name='fare',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Passenger fare in pounds', max_digits=10, null=True, verbose_name='Fare'),
        ),
        migrations.AlterField(
            model_name='predictionrecord',
            name='parch',
            field=models.IntegerField(default=0, help_text='Number of parents or children aboard', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Parents/Children Aboard'),
        ),
        migrations.AlterField(
            model_name='predictionrecord',
            name='sibsp',
            field=models.IntegerField(default=0, help_text='Number of siblings or spouses aboard', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Siblings/Spouses Aboard'),
        ),
    ]
