# Generated by Django 5.2 on 2026-02-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_remove_predictionrecord_cabin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionRecord_v2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pclass', models.IntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('age', models.FloatField(blank=True, null=True)),
                ('sibsp', models.IntegerField()),
                ('parch', models.IntegerField()),
                ('fare', models.FloatField(blank=True, null=True)),
                ('embarked', models.CharField(max_length=10)),
                ('prediction', models.IntegerField()),
                ('probability', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
