# Generated by Django 5.2 on 2026-02-12 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_predictionrecord_v2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PredictionRecord_v2',
        ),
    ]
