# Generated by Django 5.2 on 2026-02-13 10:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_delete_predictionrecord_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionrecord',
            name='rating',
            field=models.IntegerField(blank=True, help_text='User rating from 1 to 5 stars', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='User Rating'),
        ),
    ]
